# Generated by Django 2.2.2 on 2019-07-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20190701_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineid',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
    ]
