# Generated by Django 2.2.2 on 2019-07-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20190701_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='clientid',
            new_name='clientId',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machineid',
            new_name='machineId',
        ),
    ]
