# Generated by Django 2.2.2 on 2019-07-07 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20190704_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default='xEDGKGWI', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
    ]
