# Generated by Django 2.2.2 on 2019-07-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20190707_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL, verbose_name='Client id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default='u8QpAQON', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
    ]
