# Generated by Django 2.2.2 on 2019-08-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20190806_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default='1cnwg44jmwyo', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
    ]
