# Generated by Django 2.2.2 on 2019-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_auto_20190806_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='machine',
            name='spec_file1',
            field=models.FileField(blank=True, null=True, upload_to='file', verbose_name='Specifications file'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default='dke7o0nujgl3', max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True, verbose_name='Manufactured date'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='purchased_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchased date'),
        ),
    ]
