# Generated by Django 2.2.2 on 2019-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20190806_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='qrcode_image',
        ),
        migrations.AddField(
            model_name='machine',
            name='qrcode_eps',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='code/<django.db.models.fields.CharField>', verbose_name='QR code image eps'),
        ),
        migrations.AddField(
            model_name='machine',
            name='qrcode_png',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='code/<django.db.models.fields.CharField>', verbose_name='QR code image png'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default='c9ddkde9fdvs', max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
    ]
