# Generated by Django 2.2.2 on 2019-08-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_auto_20190806_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default='3yp7ifa8n4zb', max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qrcode_eps',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='code', verbose_name='QR code image eps'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qrcode_png',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='code', verbose_name='QR code image png'),
        ),
    ]
