# Generated by Django 2.2.2 on 2019-08-07 09:49

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0025_auto_20190807_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machineId',
            field=models.CharField(db_index=True, default=django.utils.crypto.get_random_string, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Machine id'),
        ),
    ]
