# Generated by Django 2.2.2 on 2019-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0026_auto_20190807_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='qrcode_eps',
            field=models.ImageField(blank=True, null=True, upload_to='code', verbose_name='QR code image eps'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='qrcode_png',
            field=models.ImageField(blank=True, null=True, upload_to='code', verbose_name='QR code image png'),
        ),
    ]
