# Generated by Django 2.2.2 on 2019-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0032_auto_20190807_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height, mm'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Length, mm'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight, mm'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width, mm'),
        ),
    ]
