# Generated by Django 2.2.2 on 2019-08-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0033_auto_20190807_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight, kg'),
        ),
    ]
