# Generated by Django 2.2.2 on 2019-08-13 06:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0035_auto_20190812_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='thumb1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format=None, keep_meta=True, null=True, quality=75, size=[300, 130], upload_to='thumb', verbose_name='Image 1 small'),
        ),
        migrations.AddField(
            model_name='machine',
            name='thumb2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format=None, keep_meta=True, null=True, quality=75, size=[300, 130], upload_to='thumb', verbose_name='Image 2 small'),
        ),
        migrations.AddField(
            model_name='machine',
            name='thumb3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, editable=False, force_format=None, keep_meta=True, null=True, quality=75, size=[300, 130], upload_to='thumb', verbose_name='Image 3 small'),
        ),
    ]
