# Generated by Django 2.2.2 on 2019-08-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0036_auto_20190813_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='thumb1',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='thumb2',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='thumb3',
        ),
    ]
